workflows:
  ios-monobank-workflow:
    name: Monobank iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "MonobankClone/MonobankClone.xcodeproj"
        XCODE_SCHEME: "MonobankClone"
        BUNDLE_ID: "com.nutipov.monobank"
      xcode: 15.0
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Build
        script: |
          set -e
          set -x
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$HOME/build/MonobankClone.xcarchive" \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Create IPA
        script: |
          set -e
          set -x
          mkdir -p "$HOME/build/ipa"
          cd "$HOME/build"
          
          # Check for assets in the archive
          echo "Checking for Assets in archive..."
          find MonobankClone.xcarchive -name "Assets.car" -o -name "AppIcon*"
          
          mkdir -p Payload
          cp -r MonobankClone.xcarchive/Products/Applications/MonobankClone.app Payload/
          
          # Verify assets in .app bundle
          echo "Checking Assets in .app bundle..."
          ls -la Payload/MonobankClone.app/ || true
          find Payload/MonobankClone.app -name "Assets.car" -o -name "AppIcon*" || true
          
          zip -r ipa/MonobankClone.ipa Payload
          rm -rf Payload
          ls -lh ipa/MonobankClone.ipa
    
    artifacts:
      - $HOME/build/ipa/*.ipa
      - $HOME/build/MonobankClone.xcarchive
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true