workflows:
  simulator-workflow:
    name: Build for iOS Simulator
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "MonobankClone/MonobankClone.xcodeproj"
        XCODE_SCHEME: "MonobankClone"
      xcode: latest
    scripts:
      - name: Build with Generic Destination for Simulator
        script: |
          set -e
          set -x
          
          cd MonobankClone
          
          # Очищаем предыдущие сборки
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
          
          # Собираем для симулятора
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            IPHONEOS_DEPLOYMENT_TARGET=15.0
            
      - name: Find and copy .app bundle
        script: |
          set -e
          
          # Находим .app файл
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "MonobankClone.app" -type d | head -1)
          
          if [ -z "$APP_PATH" ]; then
            echo "❌ .app bundle not found!"
            exit 1
          fi
          
          echo "✅ Found .app at: $APP_PATH"
          
          # Копируем в артефакты
          mkdir -p "$CM_BUILD_DIR/simulator_build"
          cp -r "$APP_PATH" "$CM_BUILD_DIR/simulator_build/"
          
          echo "📱 App bundle copied for simulator use"
          ls -la "$CM_BUILD_DIR/simulator_build/"
    
    artifacts:
      - simulator_build/*.app
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: Monobank Clone - iOS Build for Sideloadly
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "MonobankClone/MonobankClone.xcodeproj"
        XCODE_SCHEME: "MonobankClone"
        BUNDLE_ID: "com.nutipov.monobankclone"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Set up iOS 15+ deployment target
        script: |
          cd MonobankClone
          # Убеждаемся что deployment target установлен на iOS 15.0
          /usr/libexec/PlistBuddy -c "Set :objects:A1000000A:buildSettings:IPHONEOS_DEPLOYMENT_TARGET 15.0" MonobankClone.xcodeproj/project.pbxproj || echo "Deployment target already set"
          
      - name: Install CocoaPods dependencies
        script: |
          cd MonobankClone
          pod install --repo-update || echo "No Podfile found, skipping pod install"
          
      - name: Build unsigned archive for Sideloadly
        script: |
          set -e
          set -x
          
          # Очищаем предыдущие сборки
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
          
          # Создаем архив без подписи (для Sideloadly)
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/MonobankClone.xcarchive" \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE="" \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            ENABLE_BITCODE=NO
      
      - name: Create IPA for Sideloadly
        script: |
          set -e
          set -x
          
          # Создаем папку для IPA
          mkdir -p "$CM_BUILD_DIR/ipa"
          cd "$CM_BUILD_DIR"
          
          # Проверяем что архив создался
          if [ ! -d "MonobankClone.xcarchive" ]; then
            echo "❌ Archive not found!"
            exit 1
          fi
          
          echo "✅ Archive found, creating IPA..."
          
          # Создаем Payload папку
          mkdir -p Payload
          
          # Копируем .app в Payload
          cp -r MonobankClone.xcarchive/Products/Applications/MonobankClone.app Payload/
          
          # Проверяем что .app скопировался
          if [ ! -d "Payload/MonobankClone.app" ]; then
            echo "❌ App bundle not found in Payload!"
            exit 1
          fi
          
          echo "✅ App bundle copied to Payload"
          
          # Проверяем содержимое .app
          echo "📱 App bundle contents:"
          ls -la Payload/MonobankClone.app/
          
          # Проверяем Assets
          echo "🎨 Checking for Assets:"
          find Payload/MonobankClone.app -name "Assets.car" -o -name "AppIcon*" || echo "No assets found"
          
          # Создаем IPA
          zip -r ipa/MonobankClone.ipa Payload
          
          # Очищаем временные файлы
          rm -rf Payload
          
          # Проверяем размер IPA
          echo "📦 IPA created:"
          ls -lh ipa/MonobankClone.ipa
          
          # Проверяем содержимое IPA
          echo "📋 IPA contents:"
          unzip -l ipa/MonobankClone.ipa | head -20
    
    artifacts:
      - ipa/*.ipa
      - MonobankClone.xcarchive
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - nutipovottakvot@gmail.com
        notify:
          success: true
          failure: true