workflows:
  ios-workflow:
    name: iOS Build IPA for Sideloadly
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "MonobankClone/MonobankClone.xcodeproj"
        XCODE_SCHEME: "MonobankClone"
        BUNDLE_ID: "com.monobank.clone"
        EXPORT_OPTIONS_PLIST: "exportOptions.plist"
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Create export options plist
        script: |
          cat > "$EXPORT_OPTIONS_PLIST" <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>YOUR_TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftOnInstall</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
          </dict>
          </plist>
          EOL

      - name: Install dependencies
        script: |
          cd MonobankClone
          pod install || echo "No Podfile found, skipping pod install"

      - name: Build and export .ipa
        script: |
          cd MonobankClone
          
          # Clean build folder
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
          
          # Archive the app
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -archivePath "$CM_BUILD_DIR/build/MonobankClone.xcarchive" \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_ALLOWED="NO" \
            ENABLE_BITCODE=NO
          
          # Export to .ipa
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/MonobankClone.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$CM_BUILD_DIR/build/ipa" \
            -allowProvisioningUpdates
          
          # Rename output to include version
          cd "$CM_BUILD_DIR/build/ipa"
          mv "$XCODE_SCHEME.ipa" "MonobankClone.ipa"
          
          echo "IPA file created at: $(pwd)/MonobankClone.ipa"
    
    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true